name: CI/CD with Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jojomago/nextjs-github-action:latest
          file: ./Dockerfile
      - name: Deploy to Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_EC2_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker stop nextjs-docker-container || true
            docker rm nextjs-docker-container || true
            docker pull jojomago/nextjs-github-action:latest
            docker run -d -p 3000:3000 --name nextjs-docker-container jojomago/nextjs-github-action:latest